### ISSUE TITLE
Firmware.rar corrupted

### ISSUE THREAD

**Issue by MilhouseP** [TBT8A10/Research#2]
I downloaded the stock firmware rar file but when unpacking I get a corrupted error and cancels half way through. Can you please confirm the file is not corrupted and upload again.

**Comment by TBM13** [comment]
It extracts fine for me using 7-zip. Please check that your download isn't corrupted, the RAR's MD5 hash should be `A425CBB5969ADF3519D9DDBF039B2F69`

**Comment by MilhouseP** [comment]
Thank you for checking
Yes my md5 hash is a056bc7eb210c299f8325985f3a420b3
That may explain my issue
I'm re-downloading and trying again

**Comment by MilhouseP** [comment]
Thank you, I downloaded again and its all well, I haven't had time but I look forward working with this. I'll close this issue and appreciate your response.

**Comment by TBM13** [comment]
Glad to hear it!
